package com.ibm.journey.gdpr.scorer.config;

public class InputData {
	public static String text = "Rep:ThisisPriya.HowcanIhelpyou?Caller:ThisisAnand.IwanttochangemyplantocorporateplanRep:Sure,Icanhelpyou.Doyouwanttochangetheplanforthenumberfromwhichyouarecallingnow?Caller:yesRep:ForverificationpurposemayIknowyourdateofbirthandemailidCaller:Mydataofbirthis10thAugust1979andmyemailidisanand@gmail.comRep:WhichplandoyouwanttomigratetoCaller:Plan450unlimitedRep:CanIhaveyourcompanynameandemployeeidCaller:IworkforIBMandmyemployeeidis12345Rep:Ok..Ihavetakenyourrequesttomigrateplanto450unlimited.Youwillgetanupdatein3hours.IsthereanythingelsethatIcanhelpyouwithCaller:NoRep:ThanksforcallingVodaphone.Haveagoodday.Caller:youtoo";
}
